baseURL = "https://bunny-lang.org/"
theme = "bunny-theme"
title = "Bunny"
author = "rgrmrts"
copyright = "Copyright Â© 2020, Bunny Programming Language."
languageCode = "en-US"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/blog/:slug"
  tags = "/blog/:slug"

[params]
  description = "The Bunny Programming Language"
  favicon = "favicon.png"
  images = ["images/logo.png"]
  title = "bunny"
